# Generated by Django 4.2.2 on 2023-06-30 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Please enter a valid phone number.', regex='^\\+?[0-9]+$')]),
        ),
    ]
